#!/bin/bash
# alacritty-igrep
# Author: Andreas Malmqvist

TMPFILE=$(mktemp)
alacritty --title igrep -e bash -c "sk --ansi -i -c 'rg --color=always -n \"{}\"' > $TMPFILE"
cat $TMPFILE | tr : ' ' | cut -d ' ' -f 1,2

