#!/bin/bash
# alacritty-igrep
# Author: Andreas Malmqvist

TMPFILE=$(mktemp)
alacritty --title igrep -e bash -c "sk --ansi -i -c 'rg --color=always --line-number \"{}\"' > $TMPFILE"
cat $TMPFILE | cut -d : -f 1,2


