#!/bin/bash
# alacritty-find-file
# Author: Andreas Malmqvist

READFILE=$(mktemp)
WRITEFILE=$(mktemp)

if git status > /dev/null 2>&1; then
    git ls-files > $READFILE
else
	find . -type f > $READFILE
fi

st -c 'st-floated' -t 'find file' bash -c "sk < $READFILE > $WRITEFILE"
cat $WRITEFILE
