#!/bin/bash

# This scripts runs my general session for tmux
# Create the session and name the default window "music"
tmux new -s General -n music -d
tmux send-keys -t General:music "ncmpcpp -S search_engine" Enter

# Create a window in the session for "tasks"
tmux new-window -t General:2 -n tasks -d -c $HOME/Tasks
tmux send-keys -t General:tasks "vim -c VimwikiMakeDiaryNote" Enter

# Create a scratch window which will be the default window
tmux new-window -t General:3 -n scratch -c $HOME
