unbind C-b
set -g prefix C-t

set -g escape-time 0
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g base-index 1
set -g mouse on
setw -g mode-keys vi

setw -g xterm-keys on

bind C-t send-prefix
bind r source-file ~/.tmux.conf
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

bind C-e popup -E -K -R "git ls-files | fzf | xargs \
	vim --servername $(tmux display -p '#S') --remote"

set -g status on
set -g status-left ''
set -g status-right "#[bg=colour0,fg=colour3,bold] #S #[fg=colour4]#(date +%Y-%m-%d)"
set -g status-interval 1
set -g status-left-length 100
set -g status-right-length 100
set -g status-position bottom
set -g status-fg default
set -g status-bg colour8
set -g window-status-current-format '#[bg=colour0,fg=colour2,bold] #I #W#F '
set -g window-status-format '#I #W'
