# Source additional files
evaluate-commands %sh{
	KAK_DIR=$HOME/.config/kak
	SUB_DIRS="$KAK_DIR/modes $KAK_DIR/config"

	for dir in $SUB_DIRS; do
		for file in $dir/*.kak; do
			echo "source $file"
		done
	done
}

# Load additional modules
require-module file-mode
require-module xclip-mode
require-module utility-mode
